  version: "3.7"

  services:
    portainer:
      image: portainer/portainer-ce
      command: -H unix:///var/run/docker.sock
      ports:
        - "9000:9000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data

    jenkins:
      user: root
      image: "jenkinsci/blueocean"
      ports:
        - "8080:8080"
      volumes:
        - jenkins_data:/var/jenkins_home
        - /usr/bin/docker:/usr/bin/docker
        - /var/run/docker.sock:/var/run/docker.sock

  volumes:
    jenkins_data:
    portainer_data: